version: "3.9"
services:
  expense-tracker:
    build:
      context: .
    container_name: expense-tracker
    restart: unless-stopped
    environment:
      DB_SCHEMA: postgres
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - "3000:4000"
    extra_hosts:
        - "host.docker.internal:host-gateway"
